// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFMwhI0RKOaaax6ej4k35aj-6NgoTRjlU',
    appId: '1:728124903494:web:57b65b67c7931dbc917a47',
    messagingSenderId: '728124903494',
    projectId: 'chat-bot-c9a30',
    authDomain: 'chat-bot-c9a30.firebaseapp.com',
    storageBucket: 'chat-bot-c9a30.appspot.com',
    measurementId: 'G-M4N7GSTVFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWuTX1aMOAJNaSJoy6_gRkgSf3l2V6s8w',
    appId: '1:728124903494:android:2b4852de23edf8fc917a47',
    messagingSenderId: '728124903494',
    projectId: 'chat-bot-c9a30',
    storageBucket: 'chat-bot-c9a30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9fqhfG6tq1OOra6VFSMNwdm1xvfNosgE',
    appId: '1:728124903494:ios:9bf9857c5df4ed11917a47',
    messagingSenderId: '728124903494',
    projectId: 'chat-bot-c9a30',
    storageBucket: 'chat-bot-c9a30.appspot.com',
    iosBundleId: 'com.chatbot.chatbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9fqhfG6tq1OOra6VFSMNwdm1xvfNosgE',
    appId: '1:728124903494:ios:9bf9857c5df4ed11917a47',
    messagingSenderId: '728124903494',
    projectId: 'chat-bot-c9a30',
    storageBucket: 'chat-bot-c9a30.appspot.com',
    iosBundleId: 'com.chatbot.chatbot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFMwhI0RKOaaax6ej4k35aj-6NgoTRjlU',
    appId: '1:728124903494:web:8209694e9e550e1f917a47',
    messagingSenderId: '728124903494',
    projectId: 'chat-bot-c9a30',
    authDomain: 'chat-bot-c9a30.firebaseapp.com',
    storageBucket: 'chat-bot-c9a30.appspot.com',
    measurementId: 'G-49Q6M4WEDF',
  );
}
